print("¡Hola! ¿Cuánto quieres invertir?")
a = float(input("Invertirás"))
print(f"Invertirás {a} €")
print("Cual es el interés anual?")
b = float(input("El interés anual es"))
print(f"{b}")
c = int(input("Cuantos años quieres mantener la inversión?"))
print(f"Mantendrás la inversión de {a} con el interés {b} {c} años")
print(f"Tras esos años tendrás una cantidad de {a*b*c}")