version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka: 
    image: confluentinc/cp-kafka:7.3.3
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-ui-3
  #   depends_on:
  #     - kafka
  #   ports:
  #     - "8080:8080"
  #   restart: always
  #   environment:
  #     - KAFKA_CLUSTERS_0_NAME=base
  #     - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092

  # kafka-connect:
  #   image: confluentinc/cp-kafka-connect:7.3.3
  #   depends_on:
  #     - kafka
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     - CONNECT_BOOTSTRAP_SERVERS=kafka:29092
  #     - CONNECT_REST_ADVERTISED_LISTENER=http://localhost:8083
  #     - CONNECT_GROUP_ID="spark-connect-group"
  #     - CONNECT_CONFIG_STORAGE_TOPIC="connect-configs"
  #     - CONNECT_OFFSET_STORAGE_TOPIC="connect-offsets"
  #     - CONNECT_STATUS_STORAGE_TOPIC="connect-status"
  #     - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter
  #     - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.storage.StringConverter
  #   volumes:
  #     - ./kafka-connectors:/usr/share/java/kafka-connectors

networks:
  spark-net:
