# Usa una imagen base de Ubuntu
FROM ubuntu:latest

# Actualiza el sistema e instala Python
RUN apt-get update && apt-get install -y python3

# Crea el directorio de trabajo
WORKDIR /app

# Copia el script Python al contenedor
COPY sum.py /app/sum.py

# Define el comando predeterminado
ENTRYPOINT ["python3", "sum.py"]