name: dbt_project
version: '1.0'
config-version: 2

profile: dbt_project

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  dbt_project:
    +materialized: view

