services:
  ahorcado:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "jugar.py"]

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

