version: '3.8'

services:
  # Spark Master
  spark-master:
    image: bde2020/spark-master:latest
    container_name: spark-master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MODE=master
    ports:
      - "4040:4040" # Web UI
      - "7077:7077" # Spark Master Port
    volumes:
      - ../project:/opt/project
    networks:
      - spark-net

  # Spark Worker
  spark-worker:
    image: bde2020/spark-worker:latest
    container_name: spark-worker
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
    depends_on:
      - spark-master
    networks:
      - spark-net
    volumes:
      - ../project:/opt/project

  mysql:
    container_name: mysql
    image: debezium/example-mysql:2.7.3.Final
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_DATABASE=pysparkdb
     - MYSQL_USER=spark
     - MYSQL_PASSWORD=password
    networks:
      - spark-net
    restart: always


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - spark-net

networks:
  spark-net: