resource "local_file" "pet" {
  filename = var.filename[count.index]
  content  = "ESTA ES UNA NUEVA MASCOTA"
  count = length(var.filename)
}

resource "local_file" "pet_2" {
  filename = "${random_pet.my-pet.id}.txt"
  content  = "Soy un pro ${random_pet.my-pet.id}"
}

resource "random_pet" "my-pet" {
  prefix    = var.prefix
  separator = var.separator
  length    = var.length
}

output "pet-name" {
  value       = random_pet.my-pet.id
  sensitive   = false # Indica si es contenido sensible
  description = "Record the value of the pet ID generated by the random_pet resource"
  depends_on  = [
    random_pet.my-pet # Asegura que el output dependa del recurso random_pet
  ]
}
