version: '3.9'

services:
  metabase:
    image: metabase/metabase:v0.44.6
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: h2 
      MB_DB_FILE: /metabase-data/metabase.db
      MB_PLUGINS_DIR: /plugins
    restart: always
    volumes:
      - metabase_data:/metabase-data

volumes:
  metabase_data: