FROM ubuntu:latest

RUN apt-get update && apt-get install -y python3 
RUN mkdir data
WORKDIR /data

RUN touch index.html
RUN echo "<h1>Hola Docker</h1>" > index.html

EXPOSE 8000

CMD ["python3", "-m", "http.server"]