version: '3.5'

services:
  server:
    container_name: server_container
    build:
      dockerfile: Dockerfile.server
    volumes:
      - data:/data
    ports:
      - "8000:8000"
    networks:
      - my_net

  client:
    container_name: client_container
    build:
      dockerfile: Dockerfile.client
    tty: true

    networks:
      - my_net

networks:
  my_net:
 
volumes:
  data:

