services:
  app:
    build: .
    volumes:
      - ./palabras.txt:/app/palabras.txt
    environment:
      DB_HOST: db  # o la dirección de tu base de datos
      DB_PORT: 5432
      DB_NAME: hangman
      DB_USER: hangman
      DB_PASSWORD: hangman
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hangman
      POSTGRES_USER: hangman
      POSTGRES_PASSWORD: hangman
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
