name: "Prediction"

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
       - PetProject/**

jobs:
  yaml:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Run Predictions
        run: |
          pip3 install -r PetProject/requirements.txt
          python3 PetProject/quinielas.py
